name: Barry's workflow

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'

jobs:
  job1: 
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        hide-progress: false
        format: 'table'
        output: 'trivy-results.txt'
        ignore-unfixed: true
        severity: 'CRITICAL'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: barry126/app:${{ github.sha }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@v2.2.0
      with:
        cosign-release: 'v2.2.0'

    - name: Check install!
      run: cosign version

    - name: Sign image with a key
      run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
      env:
        TAGS: barry126/app:${{ github.sha }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}

    - name: Send the notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: "Image build and signed"
        SLACK_MESSAGE: |
          Name: LI CHONGYANG
          Matriculation: A0285887B
          Email: e1221699@u.nus.edu
          GitHub: https://github.com/1750067400/github-ci-cd
          Docker: https://hub.docker.com/repository/docker/barry126/app/general
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          
  job2: 
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        output: 'trivy-results.txt'
        ignore-unfixed: true
        severity: 'HIGH'

    - name: Send the notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#FF0000'
        SLACK_TITLE: "Scan failed - LI CHONGYANG"
        SLACK_MESSAGE: |
          Failed trivy scan, see uploaded report
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Upload to Slack
      uses: MeilCli/slack-upload-file@v3
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
        file_path: 'trivy-results.txt'
        initial_comment: 'Scan report by LI CHONGYANG'

